### ISSUE TITLE
raise TemplateNotFound(template), example1.py

### ISSUE THREAD

**Issue by starhh** [AKuederle/Py-Tex-automation-example#1]
Below error I encounter when executing example1.py. I have give the correct path for template as in error and .tex file exists there. Please check

```
  File "C:/Users/star/Desktop/Py-Tex-automation-example-p3/example1/example1.py", line 15, in <module>
    template = utils.get_template('C:/Users/star/Desktop/Py-Tex-automation-example-p3/example1/example1_template.tex')
  File "C:\Users\star\Desktop\Py-Tex-automation-example-p3\example1\utils.py", line 37, in get_template
    template = latex_jinja_env.get_template(os.path.realpath(template_file))
  File "C:\Users\star\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\star\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\star\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\star\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jinja2\loaders.py", line 168, in get_source
    pieces = split_template_path(template)
  File "C:\Users\star\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jinja2\loaders.py", line 31, in split_template_path
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: C:\Users\star\Desktop\Py-Tex-automation-example-p3\example1\example1_template.tex
```

**Comment by AKuederle** [comment]
I only tested that on linux. It is likely that the FileSystemLoader does not work in the way I configured it for Windows.

Try changing the following line in `utils.py`:

```
     	loader = jinja2.FileSystemLoader(os.path.abspath('/'))
```
to
```
    	loader = jinja2.FileSystemLoader(os.path.abspath(r'C:\'))
```

**Comment by starhh** [comment]
Thanks for your reply. After making the above changes in the utils.py. Below is the error which I encountered. 
```
Traceback (most recent call last):
  File "C:/Users/star/Desktop/Py-Tex-automation-example-p3/example1/example1.py", line 5, in <module>
    import utils
  File "C:\Users\star\Desktop\Py-Tex-automation-example-p3\example1\utils.py", line 35
    loader = jinja2.FileSystemLoader(os.path.abspath(r'C:\'))
                                                            ^
SyntaxError: EOL while scanning string literal 
```

**Comment by AKuederle** [comment]
Oh interesting seems like the `\` at the end is an issue can you try:
```
    loader = jinja2.FileSystemLoader(os.path.abspath(r'C:\\'))
```
(with two slashes)

**Comment by starhh** [comment]
Hi Kuederle,
Thanks for your reply, but I encounter now the below error for template not found, in fact the template is at same location. 
Please check.

```
Traceback (most recent call last):
  File "C:/Users/star/Desktop/Py-Tex-automation-example-p3/example1/example1.py", line 15, in <module>
    template = utils.get_template("C:/Users/star/Desktop/Py-Tex-automation-example-p3/example1/example1_template.tex")
  File "C:\Users\star\Desktop\Py-Tex-automation-example-p3\example1\utils.py", line 37, in get_template
    template = latex_jinja_env.get_template(os.path.realpath(template_file))
  File "C:\Users\star\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\star\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\star\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\star\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jinja2\loaders.py", line 168, in get_source
    pieces = split_template_path(template)
  File "C:\Users\star\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jinja2\loaders.py", line 31, in split_template_path
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: C:\Users\star\Desktop\Py-Tex-automation-example-p3\example1\example1_template.tex
```

**Comment by AKuederle** [comment]
That the same error we started with,,, Could you try it with relative paths instead of the absolute Path?

**Comment by starhh** [comment]
I made the below changes in utils.py file after looking at the similar example from other link http://eosrei.net/articles/2015/11/latex-templates-python-and-jinja2-generate-pdfs
loader = jinja2.FileSystemLoader(os.path.abspath('.'))
template = latex_jinja_env.get_template(template_file)

Now I am getting the below Error:

C:\Users\star\Desktop\Py-Tex-automation-example-p3\example1\.build
'pdflatex' is not recognized as an internal or external command,
operable program or batch file.

**Comment by AKuederle** [comment]
Ok nice! This means it at least finds the template.
Do you have Latex installed properly?

**Comment by starhh** [comment]
Is that separate library? I have pandas and other popular libraries.

**Comment by starhh** [comment]
I installed pylatex, but the error is same,

'pdflatex' is not recognized as an internal or external command,
operable program or batch file.

**Comment by AKuederle** [comment]
Latex has nothing to do with Python. It is a completely different program. On Windows you usually can install the MikTex Tex distribution

**Comment by starhh** [comment]
I want to stick with pip, i can not install software on my work laptop, is there a way to install latex using pip?

**Comment by AKuederle** [comment]
Latex has nothing to do with python and can not be installed via pip
